-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "allInPrice" DOUBLE PRECISION,
ADD COLUMN     "charges" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "loadingFactor" DOUBLE PRECISION NOT NULL DEFAULT 1.37,
ADD COLUMN     "pricePerSqftType" TEXT NOT NULL DEFAULT 'SBU';
