-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "sopGrowth" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sopPlanning" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sopTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
