-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "amenitiesScore" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "builderGradeScore" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "demandScore" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "infrastructureScore" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN     "locationScore" DOUBLE PRECISION NOT NULL DEFAULT 50;
